### PR TITLE
Update automation.yaml

### PR DESCRIPTION
**Pull request by sandrobonazzola**
Update automation for sdk_4.3 branch

### Requirements

* allow to run CI automation on sdk_4.3

### Description of the Change

Updated the automation.yaml file for building sdk 4.3 and push builds to the oVirt 4.3 pipeline

### Alternate Designs

No alternate design

### Benefits

Allow to build for oVirt 4.3

### Possible Drawbacks

N/A

### Verification Process

Check CI really builds from this branch and then push to 4.3 pipeline

### Applicable Issues

Related to issue #201

### CODE REVIEW

**Comment by sandrobonazzola** [comment]
ci test please

**Comment by dougsland** [comment]
@gekorob might help to review.

**Pull request merged**
