### PR TITLE
Prepare for release 4.4.3

### PR DESCRIPTION
**Pull request by imjoey**
This PR is going to make preparations for release 4.4.3. Please see `sdk/CHANGES.adoc` for details.

This PR is marked as a draft for now. The reason is this PR would revert some changes in `sdk/CHANGES.adoc`, While we would better have a further discussion on what kinds of versions need to be recorded here. Looking forward to your insights. @sandrobonazzola @mwperina  @emesika. Thanks 😄 

Signed-off-by: imjoey <majunjie@apache.org>

### CODE REVIEW

**Review by mwperina — CHANGES_REQUESTED** [review]
Wouldn't it be better to update first to model 4.4.28, which is the latest version and it's included in oVirt 4.4.6?

@emesika

**Comment by sandrobonazzola** [comment]
@imjoey I was thinking to align with oVirt Engine version but you're right, no reason to keep them aligned. May make sense to do as @mwperina suggested and align to model 4.4.28 before releasing.

**Comment by imjoey** [comment]
> Wouldn't it be better to update first to model 4.4.28, which is the latest version and it's included in oVirt 4.4.6?
> 
> 
> 
> @emesika 

@mwperina ok, +1 for me. How about I fire another new PR to bump model version? 😄

**Comment by imjoey** [comment]
> @imjoey I was thinking to align with oVirt Engine version but you're right, no reason to keep them aligned. May make sense to do as @mwperina suggested and align to model 4.4.28 before releasing.

@sandrobonazzola So you mean we continue to use 4.4.3 for new release here?

**Comment by mwperina** [comment]
> > Wouldn't it be better to update first to model 4.4.28, which is the latest version and it's included in oVirt 4.4.6?
> > @emesika
> 
> @mwperina ok, +1 for me. How about I fire another new PR to bump model version? smile

Sure, no problem with the PR, but it just makes sense to wait with the release until api-model is bumped

**Comment by imjoey** [comment]
> > > Wouldn't it be better to update first to model 4.4.28, which is the latest version and it's included in oVirt 4.4.6?
> > > @emesika
> > 
> > 
> > @mwperina ok, +1 for me. How about I fire another new PR to bump model version? smile
> 
> Sure, no problem with the PR, but it just makes sense to wait with the release until api-model is bumped

Yep, let's merge https://github.com/oVirt/ovirt-engine-sdk-go/pull/222 in prior. 😄

**Comment by sandrobonazzola** [comment]
> > @imjoey I was thinking to align with oVirt Engine version but you're right, no reason to keep them aligned. May make sense to do as @mwperina suggested and align to model 4.4.28 before releasing.
> 
> @sandrobonazzola So you mean we continue to use 4.4.3 for new release here?

No strong feelings about it, I'm fine with either just bump to 4.4.3 since last release was 4.4.2 or 4.4.6 to align with the ovirt release shipping the model used by the SDK.

**Comment by imjoey** [comment]
@mwperina @sandrobonazzola This PR is already rebased with api-model bumped to `4.4.28`. Please feel free to review. Thanks.

**Review by sandrobonazzola — APPROVED** [review]
looks good to me

**Review by mwperina — APPROVED** [review]
LGTM

**Comment by imjoey** [comment]
@emesika Could you please help to take a review in your free time? Thanks. 😄

**Comment by sandrobonazzola** [comment]
@imjoey I think you can go ahead and merge.

**Comment by imjoey** [comment]
> @imjoey I think you can go ahead and merge.

@sandrobonazzola ok, happy to. 😄

**Pull request merged**
